### ISSUE TITLE
Session Duration Issue for AWS

### ISSUE THREAD

**Issue by manjinder-mckc** [hashicorp/terraform-dynamic-credentials-setup-examples#21]
While trying this out for AWS, it seems like even though my IAM role has max duration of 12 hours, the session made by TFE still has a session expiration of 1 hour. Any thoughts ?

**Comment by SwiftEngineer** [comment]
Hello! I'm assuming you're talking specifically about the Vault-Backed Dynamic Credentials for AWS example? Is the "12 hour max duration" you are talking about set on the Vault role [here](https://github.com/hashicorp/terraform-dynamic-credentials-setup-examples/blob/main/vault-backed/aws/vault.tf#LL37C20-L37C20)?

**Comment by manjinder-mckc** [comment]
No for the native integration with AWS ([this setup ](https://github.com/hashicorp/terraform-dynamic-credentials-setup-examples/blob/main/aws/aws.tf)- [referring this document]). It seems like TFE uses default session duration (1 hour) . Wanted to know if there is a way to configure it for the native integration as described in [this document](https://developer.hashicorp.com/terraform/enterprise/workspaces/dynamic-provider-credentials/aws-configuration).

**Comment by SwiftEngineer** [comment]
I see. The session duration shouldn't be a problem for users, since the AWS terraform provider is designed to automatically renew the session via the JWT issued by TFE if it should expire (without any requests failing). The expiration of this JWT is set to the timeout of the Plan or Apply. 

Are you running into an expiration or timeout error?

**Comment by manjinder-mckc** [comment]
@SwiftEngineer Thanks for your response. Not running into error as such(since haven’t  run an apply for more than an hour yet) but I can see in CloudTrail logs that the session made my TFE using AssumeRoleUsingWebIdentity is valid only for 1 hour. Do you mean that if an apply in TFE runs for more than an hour it won’t fail and continue to run ?

**Comment by manjinder-mckc** [comment]
Yes, i tested it too and works with no issues. Closing the issue. Thanks for your help, much appreciated.
